In [1]:
import pandas as pd 
import numpy as np

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [4]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

# working with dates

In [5]:
date['date']=pd.to_datetime(date['date'])

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [7]:
#extracting the year column
date['year']=date['date'].dt.year

In [8]:
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [9]:
#extracting the months column 
date['months']=date['date'].dt.month

In [10]:
date.head()

        date  product_id  city_id  orders  year  months
0 2019-12-10        5628       25       3  2019      12
1 2018-08-15        3646       14     157  2018       8
2 2018-10-23        1859       25       1  2018      10
3 2019-08-17        7292       25       1  2019       8
4 2019-01-06        4344       25       3  2019       1

In [11]:
# extreacting months names 
date['months_name']=date['date'].dt.month_name()

In [12]:
date.head()

        date  product_id  city_id  orders  year  months months_name
0 2019-12-10        5628       25       3  2019      12    December
1 2018-08-15        3646       14     157  2018       8      August
2 2018-10-23        1859       25       1  2018      10     October
3 2019-08-17        7292       25       1  2019       8      August
4 2019-01-06        4344       25       3  2019       1     January

In [13]:
# there are many functioned like thise
#dt.day
#dt.day0fweek
#dt.weak
#dt.quarter

In [14]:
date['week_day_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,months,months_name,week_day_name
0,2019-12-10,5628,25,3,2019,12,December,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,Saturday
4,2019-01-06,4344,25,3,2019,1,January,Sunday

In [15]:
#is weekend?
date['is_weekend']=np.where(date['week_day_name'].isin(['Sunday','Saturday']),1,0)

In [16]:
date.head()

,date,product_id,city_id,orders,year,months,months_name,week_day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,Sunday,1

# working with time

In [17]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [18]:
time['date']=pd.to_datetime(time['date'])

In [19]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [20]:
time['hour']=time['date'].dt.hour

In [21]:
time.sample(5)

,date,msg,hour
795,2012-08-02 00:45:00,40л. Сейчас заберу машиной. 0994048022,0
847,2013-08-15 00:24:00,хочу любви! где ты мой мужчина? Диана,0
903,2012-07-08 02:06:00,Ева не пожалеешь 0504811555 смс ммс,2
121,2013-12-09 01:09:00,холостяк хочет познакомится 40л богат,1
11,2013-12-18 00:39:00,открою дверь прохожему который хочет погреться...,0

In [22]:
time['minute']=time['date'].dt.minute

In [23]:
time.head()

,date,msg,hour,minute
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11

In [24]:
time['second']=time['date'].dt.second

In [29]:
time.sample(5)

,date,msg,hour,minute,second
246,2015-11-11 00:50:00,М+М .днепр. пиши 093 014 76 52,0,50,0
558,2014-10-06 00:00:00,сумасшедшая капризная зато какая страстная нуж...,0,0,0
898,2015-03-30 00:07:00,д34л. познаком с м. 30-40л можно МЛС для с/о с,0,7,0
51,2015-10-18 00:57:00,м 50 поговорит с д/ж на и/т по смс Днепр 09950...,0,57,0
126,2014-11-02 01:19:00,ПОЗНАКОМЛЮСЬ С ДЕВУШКОЙ . СЕЖУ В ТЮРЬМЕ. 068-4...,1,19,0

In [30]:
time['times']=time['date'].dt.time

In [31]:
time.sample(8)

,date,msg,hour,minute,second,times
542,2013-10-21 00:48:00,обосп Ж 35 ищу М до 25 для ои Валентина,0,48,0,00:48:00
227,2014-03-20 23:28:00,:)Я девушка ищу парня от 25 до 33 зв 0988083234,23,28,0,23:28:00
133,2012-01-05 23:47:00,П 28 ПОЗН. С ДЕВУШКОЙ ДЛЯ СЕРЬЕЗНЫХ ОТНОШЕНИЙ ...,23,47,0,23:47:00
415,2012-04-01 23:52:00,А говорите могем. КУБАСОВ,23,52,0,23:52:00
688,2013-02-13 01:07:00,Тамара ты самая лучшая),1,7,0,01:07:00
103,2013-03-07 00:09:00,я М ищу Д замужн0634733074Днепр СМС.,0,9,0,00:09:00
359,2015-12-24 00:47:00,Адекватный парень познакомиться с девушкой для...,0,47,0,00:47:00
478,2012-05-29 00:08:00,познакомлюсь с красивой яркой девушкой жду фот...,0,8,0,00:08:00